#! /bin/bash

usage()
{
	cat <<EOF
Usage: ucpp init [options]
Options:
    -h, --help
        Show this message
    -t <team-number>
        Set up deploy/undeploy targets for this team's robot
EOF
}

if [ "x$1" = "x-h" ]
then
	usage
fi

if [ "x$1" = "x--help" ]
then
	usage
fi

if [ -f .ucpp ]
then
	echo "ERROR: Project already exists in `pwd`"
	echo -n "Overwrite? All customizations will be lost. (y/N)"
	read answer
	if [ "x$answer" = "xY" ] || [ "x$answer" = "xy" ]
	then
		:
	else
		exit 66
	fi
fi

source ucpp_settings

DEPLOY_IP=$(python <<EOF 2>&1 | grep "10."
s="$@"
n=int(s.split("-t")[1])
print "10.%i.%i.2\n" % (n//100, n%100)
EOF
)

export CPP_PROJECT_WS_ROOT_DIR=$(dirname "`pwd`"| sed "s|$C_DRIVE|C:/|g")
export CPP_PROJECT_ROOT_DIR=$(pwd | sed "s|$C_DRIVE|C:/|g")
export CPP_PROJECT_NAME=$(basename "`pwd`")

# Project settings (for ucpp-configure)

cat <<EOF >.ucpp
#! /bin/bash

##### Project-specific ucpp settings #####

# Workspace root directory
export CPP_PROJECT_WS_ROOT_DIR="$CPP_PROJECT_WS_ROOT_DIR"

# Project name
export CPP_PROJECT_NAME="$CPP_PROJECT_NAME"

# Project root directory
export CPP_PROJECT_ROOT_DIR="$CPP_PROJECT_ROOT_DIR"
EOF

if [ "x$DEPLOY_IP" = "x" ]
then
	:
else
	cat <<EOF >>.ucpp
# IP to deploy robot code
export DEPLOY_IP=$DEPLOY_IP
EOF
fi

cat <<EOF >>.ucpp
# Default configure method for "ucpp configure"
#   Possible values: py, winpy, wr
# Comment out to use global settings
# Leave blank to print a help message
#DEFAULT_CONFIGURE_COMMAND=

export HAVE_CPP_PROJECT=yes

EOF

# If there is no .wrmakefile, create one

if [ -f .wrmakefile ]
then
	:
else
	cp "$SCRIPT_INSTALL_DIR/.wrmakefile" .
fi

# Create a default Makefile here

cat >Makefile <<'EOF'
#UCPP makefile

# Default target
all: force
	cd PPC603gnu && exec $(MAKE) -f Makefile_linux

# Don't do anything for the "Makefile" target
Makefile: ;

# Recursively run all other targets
%: force
	cd PPC603gnu && exec $(MAKE) -f Makefile_linux "$*"

force: ;

EOF

# Create a PPC603gnu directory, if needed
mkdir -p PPC603gnu

# On Windows, don't use the Linux Makefile
case `uname` in 
	windows32|MINGW*)
		mv Makefile PPC603gnu/Makefile_tmp
		cat PPC603gnu/Makefile_tmp | sed -e "s/Makefile_linux/Makefile/g" > Makefile
		rm PPC603gnu/Makefile_tmp
		;;
	CYGWIN*)
		mv Makefile PPC603gnu/Makefile_tmp
		cat PPC603gnu/Makefile_tmp | sed -e "s/Makefile_linux/Makefile/g" |\
		sed -e 's/$(MAKE)/MAKE_CMD/' |\
		sed -e "s|MAKE_CMD|$WIND_HOME/workbench-3.0/x86-win32/bin/make.exe|"> Makefile
		rm PPC603gnu/Makefile_tmp
		;;
esac

# User diagnostics

cat <<EOF
Initialized UCPP project "$CPP_PROJECT_NAME"
  Project root directory  $CPP_PROJECT_ROOT_DIR
  Workspace directory     $CPP_PROJECT_WS_ROOT_DIR
EOF

if [ "x$DEPLOY_IP" = "x" ]
then
	:
else
	echo "  Code deployment IP      $DEPLOY_IP"
fi
