#! /bin/bash
#  Also read by GNU make - use only variable defs here

##### Global ucpp settings #####

# The location of the C:/ drive

# Under dual-boot Linux/Windows systems, set to the location of the
# C:/ drive under Linux.
export C_DRIVE=/media/sda2/

# If using gccdist, set C_DRIVE to the gccdist directory
#export C_DRIVE=/home/nikita/frc-cpp-linux/gccdist/

# Otherwise, just set to "C:/"
#export C_DRIVE=C:/


export WIND_HOME=$C_DRIVE/WindRiver
export WIND_BASE=$WIND_HOME/vxworks-6.3
export WIND_LIC_PROXY=$WIND_HOME/setup/x86-win32/bin/
export LM_LICENSE_FILE=$WIND_HOME/license/zwrsLicense.lic
export COMPILER_DIR=$WIND_HOME/gnu/3.4.4-vxworks-6.3/x86-win32/bin

# Robot IP to deploy code to
export DEPLOY_IP=

# Default configure method for "ucpp configure"
#   Possible values: py, winpy, wr
# Leave blank to print a help message
DEFAULT_CONFIGURE_COMMAND=


# Individual projects can override any of these settings

##### Don't modify these #####
export HAVE_CPP_PROJECT=no 
export SCRIPT_INSTALL_DIR=`dirname $0`
