#! /bin/bash

command="help"

if [ "x$1" = "xpy" ]
then
	command="py"
fi

if [ "x$1" = "xwinpy" ]
then
	command="winpy"
fi

if [ "x$1" = "xwr" ]
then
	command="wr"
fi


if [ "$command" = "help" ]
then
	cat <<EOF
Usage: ucpp-configure <command>
Commands:
	py:    generate Linux makefile using python script
	winpy: generate Windows makefile using python script
	wr:    modify WindRiver makefile to run on Linux
EOF
	exit
fi

##### Load Configuration #####

# Global configuration
source ucpp-settings

# Load project configuration, if it exists
if [ -f .ucpp ]
then
	source .ucpp
fi

# Anything other than "help" requires the current directory
# to be configured as a C++ project

case "x$HAVE_CPP_PROJECT" in
	xyes)
		;;
	xno)
		echo "Current directory is not configured as a C++ project"
		echo "Run ucpp-init -t <team-number>"
		exit 66
		;;
	x)
		echo "ERROR: failed to load settings"
		exit 66
		;;
esac



##### Utility functions #####

function modify_makefile() {
	# Usage: modify_makefile <input >output
	# Modifies a WindRiver makefile so that it will run under Linux

	# Add environmental variables to Makefile
	#    WIND_HOME, WIND_BASE, WIND_LIC_PROXY, LM_LICENSE_FILE

	# Set the tool path (3 occurances)
	#    TOOL_PATH = wine $COMPILER_DIR
	# "wine" is part of the tool path because the tools are .exe files

	# Perform replacements:
	#    C:/   -> $C_DRIVE (e.g. /media/sda2/)
	#    ccppc -> ccppc.exe
	#    nmppc -> "$(TOOL_PATH)nmppc.exe"

	# Remove the line:
	#    -include $(DEP_FILES)
	# TODO: figure out what it does and why it gives errors

	sed 's|WIND_HOME :=|FILE_START\n&|' | \
	sed "s|FILE_START|export WIND_HOME=$WIND_HOME\n&|" |\
	sed "s|FILE_START|export WIND_BASE=$WIND_BASE\n&|" |\
	sed "s|FILE_START|export WIND_LIC_PROXY=$WIND_LIC_PROXY\n&|" |\
	sed "s|FILE_START|export LM_LICENSE_FILE=$LM_LICENSE_FILE\n|" |\
	\
	sed "s|TOOL_PATH = |TOOL_PATH = wine $COMPILER_DIR/|g" |\
	\
	sed "s|C:/|$C_DRIVE|g" |\
	sed "s|ccppc|ccppc.exe|g" |\
	sed 's|nmppc|\$\(TOOL_PATH\)nmppc.exe|g' |\
	\
	sed 's|-include $(DEP_FILES)|##DEP_FILES not used on Linux##|g'

}

function add_deploy_target()
{
	if [ "x$DEPLOY_IP" = "x" ]
	then
		:
	else
		cat <<EOF

# Custom targets inserted by ucpp

deploy: \$(PROJECT_TARGETS)
	wput $CPP_PROJECT_NAME/Debug/$CPP_PROJECT_NAME.out ftp://anonymous@$DEPLOY_IP/ni-rt/system/FRC_UserProgram.out

EOF
	fi
}

##### Makefile generation commands #####

if [ "$command" = "py" ]
then
	echo -n "Manually generating Linux Makefile... "
	mkdir -p PPC603gnu
	python `dirname $0`/ucpp_gen_makefile.py | modify_makefile > PPC603gnu/Makefile_linux
	add_deploy_target >> PPC603gnu/Makefile_linux
	echo "Done"
fi

if [ "$command" = "winpy" ]
then
	echo -n "Manually generating Windows Makefile... "
	mkdir -p PPC603gnu
	python `dirname $0`/ucpp_gen_makefile.py > PPC603gnu/Makefile
	echo "Done"
fi

if [ "$command" = "wr" ]
then
	if [ -f PPC603gnu/Makefile ]
	then
		echo -n "Modifying WindRiver Makefile for Linux..."
		modify_makefile <PPC603gnu/Makefile >PPC603gnu/Makefile_linux
		add_deploy_target >> PPC603gnu/Makefile_linux
		echo "Done"
	else
		echo "WindRiver Makefile not found"
		echo "Generate the Makefile or use other configuration methods"
		exit 66
	fi
fi
