#! /bin/bash

usage()
{
	cat <<EOF
Usage: ucpp init [options]
Options:
    -h, --help
        Show this message
    -t <team-number>
        Set up deploy/undeploy targets for this team's robot
EOF
}

if [ "x$1" = "x-h" ]
then
	usage
fi

if [ "x$1" = "x--help" ]
then
	usage
fi

if [ -f .ucpp ]
then
	echo "ERROR: Project already exists"
	exit 66
fi

DEPLOY_IP=

ip=$(python <<EOF 2>&1 | grep "10." 
s="$@"
n=int(s.split("-t")[1])
print "10.%i.%i.2\n" % (n//100, n%100)
EOF
)

source ucpp-settings

export CPP_PROJECT_ROOT_DIR=`pwd`
export CPP_PROJECT_NAME=$(basename `pwd`)
export CPP_PROJECT_WS_ROOT_DIR=$(dirname `pwd`)

cat <<EOF | sed "s|$C_DRIVE|C:/|g" >.ucpp
#! /bin/bash

# Project-specific ucpp settings

export CPP_PROJECT_WS_ROOT_DIR=$CPP_PROJECT_WS_ROOT_DIR
export CPP_PROJECT_NAME=$CPP_PROJECT_NAME
export CPP_PROJECT_ROOT_DIR=$CPP_PROJECT_ROOT_DIR

export DEPLOY_IP=$ip

export HAVE_CPP_PROJECT=yes

EOF
