#! /bin/bash

usage()
{
	cat <<EOF
Usage: ucpp init [options]
Options:
    -h, --help
        Show this message
    -t <team-number>
        Set up deploy/undeploy targets for this team's robot
EOF
}

if [ "x$1" = "x-h" ]
then
	usage
fi

if [ "x$1" = "x--help" ]
then
	usage
fi

if [ -f .ucpp ]
then
	echo "ERROR: Project already exists"
	exit 66
fi

source ucpp-settings

DEPLOY_IP=$(python <<EOF 2>&1 | grep "10." 
s="$@"
n=int(s.split("-t")[1])
print "10.%i.%i.2\n" % (n//100, n%100)
EOF
)

export CPP_PROJECT_WS_ROOT_DIR=$(dirname `pwd`| sed "s|$C_DRIVE|C:/|g")
export CPP_PROJECT_ROOT_DIR=$(pwd | sed "s|$C_DRIVE|C:/|g")
export CPP_PROJECT_NAME=$(basename `pwd`)

cat <<EOF >.ucpp
#! /bin/bash

##### Project-specific ucpp settings #####

# Workspace root directory
export CPP_PROJECT_WS_ROOT_DIR=$CPP_PROJECT_WS_ROOT_DIR

# Project name
export CPP_PROJECT_NAME=$CPP_PROJECT_NAME

# Project root directory
export CPP_PROJECT_ROOT_DIR=$CPP_PROJECT_ROOT_DIR

# IP to deploy robot code
export DEPLOY_IP=$DEPLOY_IP

# Default configure method for "ucpp configure"
#   Possible values: py, winpy, wr
# Comment out to use global settings
# Leave blank to print a help message
#DEFAULT_CONFIGURE_COMMAND=

export HAVE_CPP_PROJECT=yes

EOF

if [ -f .wrmakefile ]
then
	:
else
	cp $SCRIPT_INSTALL_DIR/.wrmakefile .
fi

cat <<EOF
Initialized UCPP project "$CPP_PROJECT_NAME"
  Project root directory  $CPP_PROJECT_ROOT_DIR
  Workspace directory     $CPP_PROJECT_WS_ROOT_DIR
EOF

if [ "x$DEPLOY_IP" = "x" ]
then
	:
else
	echo "  Code deployment IP      $DEPLOY_IP"
fi
