#! /bin/bash

# Global
export C_DRIVE=/media/sda2/
export WIND_HOME=/media/sda2/WindRiver
export WIND_BASE=$WIND_HOME/vxworks-6.3
export WIND_LIC_PROXY=$WIND_HOME/diab/5.4.0.0/WIN32/lib
export LM_LICENSE_FILE=$WIND_HOME/license/zwrsLicense.lic
export COMPILER_DIR=$WIND_HOME/gnu/3.4.4-vxworks-6.3/x86-win32/bin

# Projects

export HAVE_CPP_PROJECT=yes

case `pwd` in
	*/FRC980/2010/frc980/workspace/FRC980* )
		export CPP_PROJECT_WS_ROOT_DIR=C:/Users/Nikita/Documents/FRC980/2010/frc980/workspace
		export CPP_PROJECT_NAME=FRC980
		export CPP_PROJECT_ROOT_DIR=$CPP_PROJECT_WS_ROOT_DIR/$CPP_PROJECT_NAME
		;;
	* )
		export HAVE_CPP_PROJECT=no
		;;
esac

# 
export SCRIPT_INSTALL_DIR=`dirname $0`